# Generated by Django 5.2.9 on 2025-12-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Closed')], default='P', max_length=1),
        ),
    ]
