# Generated by Django 5.2.9 on 2025-12-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending'),
        ),
    ]
