# Generated by Django 5.2.9 on 2026-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='phonenumber',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
